### ISSUE TITLE
ways to communicate with UEFI HV from OS?

### ISSUE THREAD

**Issue by lonnietc** [tandasat/MiniVisorPkg#13]
Hello,

I am researching some new ways to possible develop and implement a type of P2P virtual switch and you MiniVisor is very interesting as it might be something extremely unique towards this goal.

I was wondering how an OS, Windows and Linux for example, could communicate and share data back with the running hypervisor for such things as changes to running configuration like enable/disable, statistics and monitoring, etc.

Any thoughts on this?
Thanks in advance

**Comment by tandasat** [comment]
Hey. That is typically done by hypercalls, with either a shared memory or passing register values. 

For example, Microsoft Hypervisors use `VMCALL`, `RDMSR` , and `WRMSR` to pass several 64bit values via registers, and when it needs to share bit data, it uses a shared memory. Use of shared memory is done by the hypervisor providing a hypercall that returns the physical address of shared memory. Then, the NT kernel calls this hypercall, and, populates data before calling another hypercall that consumes the data in the shared memory. 

While implementations vary between hypervisors, this is a canonical approach across hypervisors and applicable to this hypervisor too. You can study more details in your choice of hypervisors (like KVM for open source, Hyper-V if you prefer Windows).

**Comment by lonnietc** [comment]
Hello @tandasat 

Thanks for the quick reply on this. 

I actually am aware of using hypercalls for various communication pathways but as I am thinking about something unique to run a thin-hypervisor ( perhaps MiniVisor ) at he UEFI level as a type of P2P vSwitch or vRouter in which it would filter some packets to pass through to the OS or route others of them to another MiniVisor on their way to their destination.  I was just wondering if MiniVisor had anything in place to allow for shared memory or hypercalls with the loaded OS.

The initial thought about having a vSwitch or vRouter built into a thin-hypervisor is that it has full control over the network device and it has been shown tht zero-copy and kernel-bypass for network systems significantly enhance the throughput and greatly reduce latency.

My ideas are to create a P2P relay mesh vpn network and really like the possibilties of running it at the UEFI level if at all possible.

I was also looking at the BitVisor code as a possible approach to build from that code-base but then came across your MiniVisor which became very interesting to explore more as well.

Perhaps we can chat more about it if you like as I have a small Slack channel set up for the project development, if you are interested.

Thanks again and have a great day.
