### ISSUE TITLE
About HalSendNMI

### ISSUE THREAD

**Issue by fly55555** [tandasat/MiniVisorPkg#6]
I can't find information about this function anywhere.
However, can the NMI interrupt be triggered only at the R0 or physical level?
Is there a way to trigger in userMode?

**Comment by tandasat** [comment]
It’s an undocumented export so you’d have to reverse engineer NT. And you cannot trigger it in user-mode on Windows as far as I know.

**Comment by fly55555** [comment]
Thanks for your answer.
