### ISSUE TITLE
Serial logs not being printed

### ISSUE THREAD

**Issue by SoftCrush** [tandasat/MiniVisorPkg#9]
Hi,

I'm trying to build MiniVisor with serial logging enabled but I can't get anything to print. I've followed your serial logging documentation and everything works and is exactly as displayed in [your picture](https://raw.githubusercontent.com/tandasat/MiniVisorPkg/master/Docs/Resources/Building_and_Testing_PuTTY_Output_with_VMware.png) except nothing is being printed to PuTTY.

I'm using VMware Workstation 16 Pro.

Any ideas? Thanks.

**Comment by tandasat** [comment]
Do you happen to configure serial connection with the port 2? Please check if the serial device for logging is in the first port (COM0) from the VMX file.
```
serial0.fileType = "file"
serial0.fileName = (path)
serial0.present = "TRUE"
```

**Comment by SoftCrush** [comment]
Seems like this was the issue. By default VMware would configure the first serial port to connect to a printer. Replacing this with the serial port I added fixed this. Thanks!
